/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 monkey.glb -t 
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ring: THREE.Mesh;
    point: THREE.Mesh;
    main: THREE.Mesh;
    main_point1: THREE.Mesh;
    main_point2: THREE.Mesh;
    mesh_0: THREE.Mesh;
    mesh_0_1: THREE.Mesh;
    mesh_0_2: THREE.Mesh;
    mesh_0_3: THREE.Mesh;
    Cylinder: THREE.Mesh;
  };
  materials: {
    Material9: THREE.MeshStandardMaterial;
    Material11: THREE.MeshStandardMaterial;
    Material5: THREE.MeshStandardMaterial;
    Material7: THREE.MeshStandardMaterial;
    Material10: THREE.MeshStandardMaterial;
    Material8: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    Material3: THREE.MeshStandardMaterial;
    Material6: THREE.MeshStandardMaterial;
  };
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>;

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/monkey.glb') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={[0.8, 0.9, 0.8]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.Material8} />
        <mesh
          geometry={nodes.mesh_0_1.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.mesh_0_2.geometry}
          material={materials.Material3}
        />
        <mesh
          geometry={nodes.mesh_0_3.geometry}
          material={materials.Material6}
          scale={[1, 1.12, 1]}
        />
      </group>
      <pointLight
        intensity={0.36}
        decay={2}
        distance={0.8}
        position={[0.309, 0.172, 0.093]}
      />
      <directionalLight intensity={1.74} position={[-0.502, -0.445, 0.936]} />
      <pointLight intensity={3.18} decay={2} position={[0, 0.426, 0]} />
      <pointLight
        intensity={0.1}
        decay={2}
        distance={1.82}
        position={[0.002, 1.655, 0.093]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0, -0.498, 0]}
        scale={[0.5, 1, 0.5]}
      />
      <mesh geometry={nodes.ring.geometry} material={materials.Material9} />
      <mesh geometry={nodes.point.geometry} material={materials.Material11} />
      <mesh geometry={nodes.main.geometry} material={materials.Material5} />
      <mesh
        geometry={nodes.main_point1.geometry}
        material={materials.Material7}
      />
      <mesh
        geometry={nodes.main_point2.geometry}
        material={materials.Material10}
      />
    </group>
  );
}

useGLTF.preload('/monkey.glb');
